# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A mininmal example
#' @param obj Numeric vector of size \eqn{K}. Coeficients in the objective function.
#' @param subj_lhs Numeric matrix of size \eqn{K\times m}. Constraints.
#' @param pname Character scalar. Name of the LP.
#' @export
#' @examples
#' obj      <- c(10, 6, 4)
#' subj_lhs <- matrix(c(1, 10, 2, 1, 4, 2, 1, 5, 6), ncol = 3)
#' subj_rhs <- c(100, 600, 300)
#'
#' # Bounds
#' cols_bnds_type <- rep(GLP_LO, 3)
#' cols_bnds_lb <- cols_bnds_ub <- rep(0.0, 3)
#'
#' rows_bnds_type <- rep(GLP_UP, 3)
#' rows_bnds_lb <- rep(0.0, 3)
#' rows_bnds_ub <- subj_rhs
#'
#' glpk_example(
#'   obj, subj_lhs, subj_rhs,
#'   cols_bnds_type, cols_bnds_lb, cols_bnds_ub,
#'   rows_bnds_type, rows_bnds_lb, rows_bnds_ub,
#'   DIR = GLP_MAX
#'   )
glpk_example <- function(obj, subj_lhs, subj_rhs, cols_bnds_type, cols_bnds_lb, cols_bnds_ub, rows_bnds_type, rows_bnds_lb, rows_bnds_ub, DIR, pname = "sample") {
    .Call(`_rcppglpk_glpk_example`, obj, subj_lhs, subj_rhs, cols_bnds_type, cols_bnds_lb, cols_bnds_ub, rows_bnds_type, rows_bnds_lb, rows_bnds_ub, DIR, pname)
}

